# Generated by Django 5.2.12 on 2026-06-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('examens', '0003_examen_semester'),
        ('portal', '0001_initial'),
        ('surveillants', '0002_surveillant_email_surveillant_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('heure_scan', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='etudiants.etudiant')),
                ('repartition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='examens.repartition')),
                ('scanne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_marquees', to='surveillants.surveillant')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('repartition', 'etudiant')},
            },
        ),
    ]
