"""
Django settings for fmpl_exam project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i^h@1akvq6728z!@ih4hn$sa$4*-h*9-xjr-$ox)7_oq5*kplt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app', 'paradox-varying-pushiness.ngrok-free.dev']

# settings.py
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Application definition
CSRF_TRUSTED_ORIGINS = ['https://paradox-varying-pushiness.ngrok-free.dev']
INSTALLED_APPS = [
    'jazzmin',
    "import_export",
    "django_extensions",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'comptes',
    'examens',
    'etudiants',
    'surveillants',
    'salles',
    'portal',
]

LOGIN_URL = '/admin/login/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fmpl_exam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fmpl_exam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    "site_title": "FMPL Examens",
    "site_header": "Gestion des Examens FMPL",
    "site_brand": "FMPL",
    "site_logo": "images/logo_white2.png",

    "welcome_sign": "Bienvenue - Gestion des Examens",

    "copyright": "Faculté de Médecine et Pharmacie Laayoune",
      # Custom CSS for login page
    "custom_css": "css/admin-custom.css",
    
    # Login form customization
    "login_logo": "images/logo.png",  # Logo on login page
    # Hide Jazzmin branding
    "show_ui_builder": False,
    
     "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "Calendrier des Examens", "url": "/examens/calendrier/"},
         {"name":"Convocation", "url": "/examens/convocations/"},
    ], 

    # Custom icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    
    # Theme customization
    "theme": "flatly",  # or "darkly", "flatly", "simplex", etc.
    "dark_mode_theme": "darkly",
}

# settings.py
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── Email (Gmail SMTP) ────────────────────────────────────────────
EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST       = 'smtp.gmail.com'
EMAIL_PORT       = 587
EMAIL_USE_TLS    = True
EMAIL_HOST_USER  = 'aitider99@gmail.com'       # ← ton Gmail
EMAIL_HOST_PASSWORD = 'vxtx wddq qeto tpqd'    # ← App Password Gmail (pas ton vrai mot de passe)
DEFAULT_FROM_EMAIL = 'FMPL Laâyoune <aitider99@gmail.com>'

# ── WhatsApp (Twilio) ─────────────────────────────────────────────
TWILIO_ACCOUNT_SID  = ''  # ← depuis dashboard Twilio
TWILIO_AUTH_TOKEN   = ''
TWILIO_WHATSAPP_FROM = 'whatsapp:+14155238886'  # numéro sandbox Twilio

