# Generated by Django 5.2.12 on 2026-06-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amphi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='siege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siege_number', models.IntegerField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/sieges/')),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to='salles.amphi')),
            ],
            options={
                'ordering': ['siege_number'],
                'unique_together': {('amphi', 'siege_number')},
            },
        ),
    ]
