# Generated by Django 5.2.12 on 2026-05-16 22:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/seats/')),
                ('qr_code_data', models.TextField(blank=True, editable=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='salles.amphi')),
            ],
            options={
                'ordering': ['amphi', 'seat_number'],
                'unique_together': {('amphi', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='salles.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
            ],
            options={
                'ordering': ['-reserved_at'],
                'unique_together': {('seat', 'exam')},
            },
        ),
    ]
