# Generated by Django 5.2.12 on 2026-05-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='qr_code_data',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='SeatReservation',
        ),
    ]
