# Generated by Django 5.2.12 on 2026-06-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('salles', '0001_initial'),
        ('surveillants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('rattrapage', 'Rattrapage')], default='normal', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=150)),
                ('semester', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4'), ('5', 'Semestre 5'), ('6', 'Semestre 6'), ('7', 'Semestre 7'), ('8', 'Semestre 8'), ('9', 'Semestre 9'), ('10', 'Semestre 10'), ('11', 'Semestre 11'), ('12', 'Semestre 12')], default='1', max_length=2, verbose_name='Semestre')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('niveau', models.CharField(choices=[('1', '1ère Année'), ('2', '2ème Année'), ('3', '3ème Année'), ('4', '4ème Année'), ('5', '5ème Année')], max_length=2)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.annee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='examens.session')),
            ],
        ),
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.amphi')),
                ('etudiants', models.ManyToManyField(blank=True, to='etudiants.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
                ('surveillants', models.ManyToManyField(to='surveillants.surveillant')),
            ],
        ),
        migrations.CreateModel(
            name='Repartitionsiege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
                ('repartition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siege_assignments', to='examens.repartition')),
                ('siege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.siege')),
            ],
            options={
                'unique_together': {('repartition', 'etudiant'), ('repartition', 'siege')},
            },
        ),
    ]
