# Generated by Django 5.2.12 on 2026-05-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('salles', '0001_initial'),
        ('surveillants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('rattrapage', 'Rattrapage')], default='normal', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.annee')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='examens.session')),
            ],
        ),
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.amphi')),
                ('etudiants', models.ManyToManyField(blank=True, to='etudiants.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen')),
                ('surveillants', models.ManyToManyField(to='surveillants.surveillant')),
            ],
        ),
    ]
