# Generated by Django 5.2.12 on 2026-06-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repartition',
            unique_together={('examen', 'amphi')},
        ),
    ]
