# Generated by Django 5.2.12 on 2026-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='niveau',
            field=models.CharField(choices=[('1', '1ère Année'), ('2', '2ème Année'), ('3', '3ème Année'), ('4', '4ème Année'), ('5', '5ème Année')], max_length=2),
        ),
    ]
