# Generated by Django 5.2.12 on 2026-05-16 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('examens', '0001_initial'),
        ('salles', '0001_initial'),
        ('surveillants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition',
            name='amphi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.amphi'),
        ),
        migrations.AddField(
            model_name='repartition',
            name='etudiants',
            field=models.ManyToManyField(blank=True, to='etudiants.etudiant'),
        ),
        migrations.AddField(
            model_name='repartition',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.examen'),
        ),
        migrations.AddField(
            model_name='repartition',
            name='surveillants',
            field=models.ManyToManyField(to='surveillants.surveillant'),
        ),
        migrations.AddField(
            model_name='examen',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='examens.session'),
        ),
    ]
