# Generated by Django 5.2.12 on 2026-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='semester',
            field=models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2'), ('3', 'Semestre 3'), ('4', 'Semestre 4'), ('5', 'Semestre 5'), ('6', 'Semestre 6'), ('7', 'Semestre 7'), ('8', 'Semestre 8'), ('9', 'Semestre 9'), ('10', 'Semestre 10'), ('11', 'Semestre 11'), ('12', 'Semestre 12')], default='1', max_length=2, verbose_name='Semestre'),
        ),
    ]
