# Generated by Django 5.2.12 on 2026-06-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
        ('examens', '0003_examen_semester'),
        ('salles', '0002_alter_seat_options_remove_seat_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepartitionSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
                ('repartition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='examens.repartition')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.seat')),
            ],
            options={
                'unique_together': {('repartition', 'etudiant'), ('repartition', 'seat')},
            },
        ),
    ]
