# Generated by Django 5.2.12 on 2026-06-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
