# Generated by Django 5.2.12 on 2026-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillant',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='surveillant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
