# Generated by Django 5.2.12 on 2026-04-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_universitaire', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('apogee', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.annee')),
            ],
        ),
    ]
