# Generated by Django 5.2.12 on 2026-06-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=100)),
                ('annee_universitaire', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Année universitaire',
                'verbose_name_plural': 'Années universitaires',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('apogee', models.CharField(max_length=20)),
                ('niveau', models.CharField(choices=[('1', '1ère Année'), ('2', '2ème Année'), ('3', '3ème Année'), ('4', '4ème Année'), ('5', '5ème Année')], max_length=2)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.annee')),
            ],
        ),
    ]
