# Generated by Django 5.2.12 on 2026-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annee',
            old_name='nom',
            new_name='filiere',
        ),
    ]
