# Generated by Django 5.2.12 on 2026-06-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
